-- Schema for a minimal TR-069 ACS (MySQL)
CREATE TABLE IF NOT EXISTS devices (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  oui VARCHAR(6) NOT NULL,
  product_class VARCHAR(64) DEFAULT NULL,
  serial_number VARCHAR(128) NOT NULL,
  username VARCHAR(128) DEFAULT NULL,
  ip_address VARCHAR(45) DEFAULT NULL,
  sw_version VARCHAR(128) DEFAULT NULL,
  hw_version VARCHAR(128) DEFAULT NULL,
  first_inform DATETIME DEFAULT CURRENT_TIMESTAMP,
  last_inform DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_device (oui, serial_number, product_class)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS events (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  device_id INT UNSIGNED NOT NULL,
  event_code VARCHAR(128) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS parameters (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  device_id INT UNSIGNED NOT NULL,
  name VARCHAR(255) NOT NULL,
  value TEXT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY device_param_unique (device_id, name),
  FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
